input:
  type: pptx
  path: samples/from_pptx/sample.pptx

output:
  speaker_id: 3
  speaker_speed: 1.1
  path: from_pptx.mp4
  fps: 1
  manuscript_slide_margin: 0.8
  manuscript_line_interval: 0.4


